name: Flutter Build

on:
  push:
    branches: [ main ]

jobs:

  linux-android-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor

      - run: flutter pub get

      # WEB
      - run: flutter build web --release

      # ANDROID (ARM32 + ARM64)
      - run: flutter build apk --release --target-platform android-arm
      # ,android-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: android-web-build
          path: |
            build/web
            build/app/outputs/flutter-apk/*.apk


  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor

      - run: flutter config --enable-windows-desktop

      - run: flutter pub get

      - run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release