name: Flutter Build

on:
  push:
    branches: [ main ]


jobs:

  android-arm32:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor
      - run: flutter pub get

      - run: flutter build apk --release --target-platform android-arm

      - uses: actions/upload-artifact@v4
        with:
          name: android-arm32-apk
          path: build/app/outputs/flutter-apk/*.apk



  android-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor
      - run: flutter pub get

      - run: flutter build apk --release --target-platform android-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: android-arm64-apk
          path: build/app/outputs/flutter-apk/*.apk



  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor
      - run: flutter pub get

      - run: flutter build web --release

      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web



  linux-x64:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install Linux deps
      run: |
        sudo apt update
        sudo apt install -y \
          clang \
          cmake \
          ninja-build \
          pkg-config \
          libgtk-3-dev \
          liblzma-dev

    - run: flutter doctor

    - run: flutter config --enable-linux-desktop
    - run: flutter pub get

    - run: flutter build linux --release

    - uses: actions/upload-artifact@v4
      with:
        name: linux-x64-build
        path: build/linux/x64/release/bundle



  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get

      - run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release

# name: Flutter Build

# on:
#   push:
#     branches: [ main ]


# jobs:

#   android-arm32:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - run: flutter doctor
#       - run: flutter pub get

#       - run: flutter build apk --release --target-platform android-arm

#       - uses: actions/upload-artifact@v4
#         with:
#           name: android-arm32-apk
#           path: build/app/outputs/flutter-apk/*.apk



#   web:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - run: flutter doctor
#       - run: flutter pub get

#       - run: flutter build web --release

#       - uses: actions/upload-artifact@v4
#         with:
#           name: web-build
#           path: build/web



#   windows:
#     runs-on: windows-latest

#     steps:
#       - uses: actions/checkout@v4

#       - uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - run: flutter doctor

#       - run: flutter config --enable-windows-desktop
#       - run: flutter pub get

#       - run: flutter build windows --release

#       - uses: actions/upload-artifact@v4
#         with:
#           name: windows-build
#           path: build/windows/x64/runner/Release